#!/usr/bin/env bash
#
# jarvis deploy helper.
#   deploy.sh env     — create/fill the root .env (interactive; FORCE=1 overwrites)
#   deploy.sh build   — build the app image
#   deploy.sh ssl     — issue the Let's Encrypt certificate (idempotent)
#   deploy.sh up      — start all services
#   deploy.sh down    — stop all services
#   deploy.sh logs    — tail logs
#   deploy.sh all     — full first deploy: env + build + ssl + up   (default)
#
# Values can be supplied non-interactively by exporting them first, e.g.
#   DOMAIN=jarvis.example.com TELEGRAM_BOT_TOKEN=... OPENROUTER_API_KEY=... \
#   ADMIN_USER_IDS=123 LETSENCRYPT_EMAIL=me@example.com ./deploy/deploy.sh all
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"
cd "$ROOT"

log()  { printf '\033[1;34m[deploy]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[deploy]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[deploy]\033[0m %s\n' "$*" >&2; exit 1; }

compose() { docker compose "$@"; }

# Host-visible persistent state lives under ./data (DB + SSL certs + ACME webroot).
ensure_dirs() { mkdir -p "$ROOT/data/db" "$ROOT/data/letsencrypt" "$ROOT/data/certbot-www"; }

require_docker() {
  command -v docker >/dev/null 2>&1 || die "docker not found — install Docker first."
  docker compose version >/dev/null 2>&1 || die "'docker compose' (v2) not available."
}

# ask VAR "Prompt" required|optional plain|secret "default"
# Prefers an already-exported env var; otherwise prompts (prompt → stderr, value → stdout).
ask() {
  local var="$1" desc="$2" req="$3" kind="${4:-plain}" def="${5:-}"
  local cur="${!var:-}"
  if [ -n "$cur" ]; then printf '%s' "$cur"; return; fi
  if [ ! -t 0 ]; then
    [ "$req" = required ] && die "$var is required (no TTY — export $var or set it in .env)."
    printf '%s' "$def"; return
  fi
  local val=""
  while :; do
    if [ "$kind" = secret ]; then
      printf '%s%s: ' "$desc" "${def:+ [keep current]}" >&2
      read -rs val; printf '\n' >&2
    else
      printf '%s%s: ' "$desc" "${def:+ [$def]}" >&2
      read -r val
    fi
    [ -z "$val" ] && val="$def"
    if [ -z "$val" ] && [ "$req" = required ]; then warn "value required."; continue; fi
    break
  done
  printf '%s' "$val"
}

ensure_env() {
  if [ -f "$ENV_FILE" ] && [ "${FORCE:-}" != 1 ]; then
    log ".env already exists — keeping it (re-provision with: FORCE=1 deploy/deploy.sh env)."
    return 0
  fi
  log "Provisioning $ENV_FILE"
  # Seed prompt defaults from an existing .env if present.
  if [ -f "$ENV_FILE" ]; then set -a; . "$ENV_FILE"; set +a; fi

  local domain email staging bot openrouter admins zai openai xai google
  domain=$(ask DOMAIN "Public domain (e.g. jarvis.example.com)" required plain "${DOMAIN:-}")
  email=$(ask LETSENCRYPT_EMAIL "Let's Encrypt e-mail" required plain "${LETSENCRYPT_EMAIL:-}")
  staging=$(ask CERTBOT_STAGING "Use Let's Encrypt staging (testing)? 1=yes, empty=no" optional plain "${CERTBOT_STAGING:-}")
  bot=$(ask TELEGRAM_BOT_TOKEN "Telegram bot token (@BotFather)" required secret "${TELEGRAM_BOT_TOKEN:-}")
  openrouter=$(ask OPENROUTER_API_KEY "OpenRouter API key" required secret "${OPENROUTER_API_KEY:-}")
  admins=$(ask ADMIN_USER_IDS "Admin Telegram user id(s), comma-separated" required plain "${ADMIN_USER_IDS:-}")
  zai=$(ask ZAI_API_KEY "Z.AI API key (optional)" optional secret "${ZAI_API_KEY:-}")
  openai=$(ask OPENAI_API_KEY "OpenAI API key (optional)" optional secret "${OPENAI_API_KEY:-}")
  xai=$(ask XAI_API_KEY "xAI API key (optional)" optional secret "${XAI_API_KEY:-}")
  google=$(ask GOOGLE_API_KEY "Google API key (optional)" optional secret "${GOOGLE_API_KEY:-}")

  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by deploy/deploy.sh — secrets, do NOT commit.
DOMAIN=$domain
LETSENCRYPT_EMAIL=$email
CERTBOT_STAGING=$staging

TELEGRAM_BOT_TOKEN=$bot
TELEGRAM_USE_WEBHOOK=${TELEGRAM_USE_WEBHOOK:-}
TELEGRAM_WEBHOOK_URL=${TELEGRAM_WEBHOOK_URL:-}

OPENROUTER_API_KEY=$openrouter
ZAI_API_KEY=$zai
OPENAI_API_KEY=$openai
XAI_API_KEY=$xai
GOOGLE_API_KEY=$google

ADMIN_USER_IDS=$admins

NODE_ENV=production
LOG_LEVEL=${LOG_LEVEL:-info}
PORT=${PORT:-8080}
LIBSQL_URL=${LIBSQL_URL:-file:/data/avocado.db}
LIBSQL_AUTH_TOKEN=${LIBSQL_AUTH_TOKEN:-}
EOF
  chmod 600 "$ENV_FILE"
  log "Wrote $ENV_FILE (chmod 600)."
}

cmd="${1:-all}"

require_docker
case "$cmd" in
  env)   ensure_env ;;
  build) compose build ;;
  ssl)   [ -f "$ENV_FILE" ] || ensure_env; ensure_dirs; "$ROOT/deploy/init-letsencrypt.sh" ;;
  up)    ensure_dirs; compose up -d ;;
  down)  compose down ;;
  logs)  compose logs -f --tail=100 ;;
  all|deploy)
    ensure_env
    ensure_dirs
    log "Building images…";          compose build
    log "Ensuring SSL certificate…"; "$ROOT/deploy/init-letsencrypt.sh"
    log "Starting services…";        compose up -d
    domain=$(grep -E '^DOMAIN=' "$ENV_FILE" | cut -d= -f2-)
    log "Done → https://$domain   (admin Mini App via @BotFather menu button)"
    ;;
  *) die "unknown command '$cmd' (use: env|build|ssl|up|down|logs|all)" ;;
esac
